name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show Linux version
      run: uname -r
    - name: build kernel
      run: make clean all -C ./tp_exam/
      