name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: display files
      run: ls -la 
    - name: move to kernel
      run: cd tp_exam
    - name: make kernel
      run: make clean all
