name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-kernel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Gives execution privilige to script
      run: chmod +x ./build-image.sh 

    - name: Build the Docker image
      run: sudo ./build-image.sh
    
    - name: Check images 
      run: docker image history 32bit/ubuntu:bionic

    - name: Launch test in docker
      run: docker run -i 32bit/ubuntu:bionic sh
