name: Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installs GCC multilib
      run: sudo apt-get install gcc-multilib

    - name: Add +x to script
      run: chmod +x unit_test/test_script.sh 

    - name: Launch make file for test
      run: make -C ./unit_test